security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        # in_memory:
        #     memory:
        #         users:
        #             test:
        #                 password: test
        #                 roles: 'ROLE_USER'
        our_db_provider:
            entity:
                class: UserBundle:User
                property: username
    encoders:
        UserBundle\Entity\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        public:
            pattern: ^/public
            security: false

        api:
            pattern: ^/api
            security: false

        default:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: /login
                check_path: /login_check

            logout: ~
            provider: our_db_provider

    access_control:
         # for csrf whitelisting
         - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/api, roles: ROLE_API }
         - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED  }
