security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    test:
                        password: test
                        roles: 'ROLE_USER'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        public:
            pattern: ^/public
            security: false

        api:
            pattern: ^/api
            security: false

        default:
            pattern: ^/
            http_basic: ~
            logout: ~

    access_control:
         # for csrf whitelisting
         - { path: ^/api, roles: ROLE_API }
